# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("""
CREATE TABLE "ghec_viewer_measure" (
    "id" integer NOT NULL PRIMARY KEY,
    "the_geom" geometry,
    "en" varchar(255) NOT NULL,
    "src" varchar(255) NOT NULL,
    "yea" integer NOT NULL,
    "mon" integer,
    "day" integer,
    "hou" integer,
    "min" integer,
    "sec" double precision,
    "are" varchar(255),
    "lat" double precision NOT NULL,
    "lon" double precision NOT NULL,
    "latunc" double precision,
    "lonunc" double precision,
    "epdet" varchar(5),
    "dep" double precision,
    "io" varchar(255),
    "msrc" varchar(255) NOT NULL,
    "m" double precision NOT NULL,
    "munc" double precision,
    "mtyp" varchar(5),
    "mdet" varchar(5),
    "mdpsrc" varchar(255),
    "mdpn" integer,
    "mdpix" varchar(255),
    "mdpsc" varchar(5),
    "rem" varchar(1024),
    CONSTRAINT enforce_dims_the_geom CHECK ((st_ndims(the_geom) = 2)),
    CONSTRAINT enforce_geotype_the_geom CHECK (((geometrytype(the_geom) = 'POINT'::text) OR (the_geom IS NULL))),
    CONSTRAINT enforce_srid_the_geom CHECK ((st_srid(the_geom) = 4326))
);
        """,
                          reverse_sql="""
DROP TABLE "ghec_viewer_measure";
"""),
    ]
